import { useEffect, useState } from 'react';
import axios from 'axios';
import { Link } from 'react-router-dom';

function Dashboard() {
  const [patients, setPatients] = useState([]);
  const [todaysSessions, setTodaysSessions] = useState([]);
  const [filterAnomalies, setFilterAnomalies] = useState(false);
  useEffect(() => { axios.get('http://localhost:5000/api/patients').then(({ data }) => setPatients(data)).catch(console.error); axios.get('http://localhost:5000/api/sessions/today').then(({ data }) => setTodaysSessions(data)).catch(console.error); }, []);
  const displayedSessions = filterAnomalies ? todaysSessions.filter(({ anomalies }) => anomalies?.length) : todaysSessions;
  const status = (startTime, endTime) => { const now = new Date(); const start = new Date(startTime); const end = endTime && new Date(endTime); if (!end || now > end) return ['Completed', 'status-complete']; if (now < start) return ['Scheduled', 'status-pending']; return ['In progress', 'status-active']; };
  return <><section className="dashboard-hero"><span className="hero-label">TODAY AT A GLANCE</span><h2>Dialysis care, made clear.</h2><p>Review today’s treatment schedule and bring attention to sessions that need follow-up.</p><div className="schedule-toolbar"><span>{todaysSessions.length} session{todaysSessions.length === 1 ? '' : 's'} scheduled today</span><label className="filter-control"><input type="checkbox" checked={filterAnomalies} onChange={(e) => setFilterAnomalies(e.target.checked)} /> Show alerts only</label></div></section><section><div className="section-title"><h2>Today’s schedule</h2><span>{filterAnomalies ? 'Alert view' : 'All sessions'}</span></div>{displayedSessions.length === 0 ? <div className="empty-state">{filterAnomalies ? 'No clinical alerts were found in today’s schedule.' : 'No sessions are scheduled for today.'}</div> : <ul className="session-list">{displayedSessions.map((session) => { const [label, statusClass] = status(session.startTime, session.endTime); return <li className="session-card" key={session._id}><div className="card-top"><strong className="card-name">{session.patientId?.name || 'Unknown patient'}</strong><span className={`status ${statusClass}`}>{label}</span></div><div className="session-meta"><span><b>Time</b> {new Date(session.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}{session.endTime && ` – ${new Date(session.endTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`}</span><span><b>Machine</b> {session.machineId}</span><span><b>BP</b> {session.systolicBP}/{session.diastolicBP}</span><span><b>Pre-weight</b> {session.preWeight} kg</span></div>{session.anomalies?.length > 0 && <div className="alert-box">Clinical alert: {session.anomalies.join(' · ')}</div>}</li>; })}</ul>}</section><section className="patient-section"><div className="section-title"><h2>Registered patients</h2><span>{patients.length} total</span></div>{patients.length === 0 ? <div className="empty-state">No patients have been registered yet.</div> : <ul className="patient-list">{patients.map((patient) => <li className="patient-card" key={patient._id}><Link to={`/patient/${patient._id}`}><strong>{patient.name}</strong><span>MRN {patient.mrn} · Dry weight {patient.dryWeight} kg</span></Link></li>)}</ul>}</section></>;
}
export default Dashboard;
